### ISSUE TITLE
Design page for after muting a thread from an email

### ISSUE THREAD

**Issue by lachlanjc** [withspectrum/spectrum#2744] opened 2018-04-05 16:59 UTC
This page can be very simple, but a little Spectrum styling would go a long way 🙂
![f643055f-9c1c-43bf-aca2-0c8c9ada40c4](https://user-images.githubusercontent.com/5074763/38380265-38c33288-38d1-11e8-9e3e-15fa6adcac98.png)

**Comment by brianlovin** [comment] 2018-04-05 17:04
Agreed! A lot of those should honestly just be redirects, too, but I haven't taken the time to figure out a system on the client side for showing a 'successfully unsubscribed' badge or banner of some sort.

**Comment by brianlovin** [comment] 2018-05-04 22:25
Duplicate of #1954

**Closed by brianlovin** 2018-05-04 22:25 UTC
Labels: Feature
