### ISSUE TITLE
Threads crashing spectrum

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3127] opened 2018-05-21 15:53 UTC
- https://spectrum.chat/?t=f58380fe-be5d-4b87-91ee-e2f2423014d4 crashes entire app
<img width="641" alt="screenshot 2018-05-21 09 54 14" src="https://user-images.githubusercontent.com/1923260/40316884-efceed26-5cdc-11e8-96bd-53fb5ccc66d3.png">

- https://spectrum.chat/?t=5bb0b1a0-c897-4262-a397-707d61fdac34 crashes the chat input
<img width="623" alt="screenshot 2018-05-21 09 55 23" src="https://user-images.githubusercontent.com/1923260/40316936-1a44e416-5cdd-11e8-8ec8-f5ac57b742dd.png">

**Comment by alejandronanez** [comment] 2018-05-21 16:06
FWIW, the empty body seems to be the root cause of this.

![screen shot 2018-05-21 at 11 06 02 am](https://user-images.githubusercontent.com/464978/40317390-f7c8f79c-5ce6-11e8-9f97-35473d6b3d6a.png)

**Comment by brianlovin** [comment] 2018-05-21 16:11
I know the cause of the first one:

If a user composes a thread on Android, the thread type is set to `TEXT`. In the mutation, we check for these text types and convert them to draft state. However, the logic is this:

```js
if (type === 'TEXT') {
    type = 'DRAFTJS';
    if (thread.content.body) {
      thread.content.body = JSON.stringify(
        markdownToDraft(thread.content.body)
      );
    }
  }
```

As you can see, a thread composed on android without a body will not have any draft state set as the `content.body`, which crashes everything on the frontend.

A thread without a body should be converted to draftjs state like so:

```js
"content": {
  "body": "{"blocks":[{"key":"foo","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}" ,
  "title":  "Test"
} ,
```

cc @mxstbr :)

**Comment by mxstbr** [comment] 2018-05-21 16:15
Let's add a resolver for the `body` field that returns `"{}"` if the body in the db is `""` and the type is draft, that should fix it immediately for everybody?

**Comment by brianlovin** [comment] 2018-05-21 16:17
I will try

**Comment by brianlovin** [comment] 2018-05-21 16:17
I will try locally now.

**Comment by alejandronanez** [comment] 2018-05-21 16:33
@brianlovin @mxstbr I managed to replicate the chat issue locally. Create a thread and **only** add a block of code in the body.

**Comment by brianlovin** [comment] 2018-05-21 16:34
@alejandronanez hm I can't repro with that step - I'm still able to type in the chat input

**Comment by alejandronanez** [comment] 2018-05-21 16:37
Try this:

1. Create the thread with only a block of code in it
2. Refresh the page
3. Click the chat input.

![chat-input-error](https://user-images.githubusercontent.com/464978/40318763-51aa87fe-5ceb-11e8-9bdd-8d85146f6229.gif)

:)

**Comment by brianlovin** [comment] 2018-05-21 16:39
Ah, it needed a refresh. Good call - this is *super* weird cc @mxstbr

**Comment by brianlovin** [comment] 2018-05-21 16:41
Here's the warning:
<img width="1300" alt="screenshot 2018-05-21 10 40 37" src="https://user-images.githubusercontent.com/1923260/40318883-6b6d00b6-5ce3-11e8-95bc-b254c2b204d2.png">

And deprecation link: https://www.chromestatus.com/features/6680566019653632

Digging in to see if other people are experiencing this....although it's bizarre that the thread content would impact the chat input in this way.

**Comment by brianlovin** [comment] 2018-05-21 16:41
Another interesting side effect of this:

if you create a thread where the body is only a code block, then you go to edit the thread, it's not possible to escape the code block.

**Comment by mxstbr** [comment] 2018-06-01 11:43
This was fixed in https://github.com/withspectrum/draft-js-markdown-plugin/pull/84!

**Closed by mxstbr** 2018-06-01 11:43 UTC
Labels: Bug, Bug: FIX NOW
