### ISSUE TITLE
Prevent infinite nesting of modal routes

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4792] opened 2019-03-04 03:44 UTC
If you open the watercooler thread in the thread modal, then click on a thread attachment, it starts to break our routing and overlays content on top of itself. We should prevent this. I think there's a relatively straightforward way to do this. In our `routes.js` file we should indicate that the view is being shown in a modal:

```js
{isModal && (
  <Route
    path="/new/thread"
    render={props => <ComposerFallback {...props} isModal={true} />}
  />
)}
```

And then when we construct the links further down the tree we get that prop and use it to set the modal state:

```
to={{
  pathname: 'foo',
  search: qs.stringify({ bar: 'biz' }),
  state: { isModal: !this.props.isModal })
}}
```

Or something like that...

**Comment by mxstbr** [comment] 2019-03-04 09:28
This actually works as intended, we are not infinitely stacking modals, we only ever render one and swap out the content.

What is not working is closing the slider. We call `history.goBack` when you press the overlay or ESC, but if the last item was a modal we show that, which sucks.

The solution is to show the last non-modal route when you click on the overlay or press "ESC"!

**Closed** 2019-03-05 16:09 UTC
Labels: Bug
