### ISSUE TITLE
Text not clearing from comment input

### ISSUE THREAD

**Issue by iamjoshfrank** [withspectrum/spectrum#2815] opened 2018-04-11 00:11 UTC
On Chrome for Android (Samsung S7 Edge), after typing several words, when attempting to backspace to edit, only a few characters would be deleted then they were replaced repeatedly.

When reloading the page, the input maintained the garbled text. When navigating to a new topic, the input maintained the same garbled text.

Occurred while using Spectrum from a home screen app as well as after opening the app in a normal Chrome tab.

Will try to attach a screenshot or GIF/video capture.

**Comment by iamjoshfrank** [comment] 2018-04-11 00:12
![screenshot_20180410-185816](https://user-images.githubusercontent.com/10236515/38589831-11607be4-3cf3-11e8-8115-64bd851b41f7.png)

**Comment by brianlovin** [comment] 2018-04-11 00:13
Hey @iamjoshfrank - thanks for the report! This is a duplicate of two issues: #2723 and #2680 ; these are definitely annoying, so sorry for the troubles right now! I'm going to close this so we can move discussions over to those respective issues

**Closed by brianlovin** 2018-04-11 00:13 UTC
Labels: Bug

**Comment by iamjoshfrank** [comment] 2018-04-11 01:28
Oh thanks @brianlovin ! I did a few fast searches before opening this issue but must have been searching against "keyboard" and other keywords. I'll keep my eye out for updates on 2723 and 2680.
