### ISSUE TITLE
Converting from raw to draft state is crashing the app

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4570] opened 2019-01-24 02:00 UTC
@mxstbr somehow this thread "c6f828ab-f0bd-4b75-bb21-ac1d276efe6e" is crashing the app. I pulled it up in the db and it's not immediately obvious what part of the thread body is crashing the app. Could I get your help to look into this?

**Comment by brianlovin** [comment] 2019-01-24 02:02
Since this is the most recently updated thread in the spectrum support community, it's crashing the app quite a lot for anyone who views the community or is a member of it and loads their inbox. going to manually mark it as deleted in the db for now

**Comment by brianlovin** [comment] 2019-01-24 02:59
Another broken thread: 298e1410-3ff6-4868-81d0-e6b8b0be4339

**Comment by brianlovin** [comment] 2019-01-24 03:00
Another broken thread: 8a2058b2-6e99-44e1-9adc-4aa05c042b8c

**Comment by mxstbr** [comment] 2019-01-24 07:49
I know what this is. I broke Android users creating plaintext threads while moving to the plaintext chat input.

I fixed this bug in #4564, but didn't realize it was breaking stuff. Will cherry-pick and hotfix deploy.

**Comment by mxstbr** [comment] 2019-01-24 08:03
There are 12 broken threads in the prod db, see this query:

```JS
r.db('spectrum').table('threads')
  .filter(thread => thread('content')('body').match('"blockMap":'))
```

**Comment by mxstbr** [comment] 2019-01-24 08:14
Hotfix is deployed to prod (that took a while due to npm registry issues...), digging into converting the 12 broken threads manually now

**Comment by mxstbr** [comment] 2019-01-24 09:02
Fixed threads:

- 278cc631-83ab-4dc3-bad2-ec248accaa1f
- 2f1952a0-6d5f-4d1e-beec-ac18a30786e8
- 9573539a-9937-4904-bc1f-90677d82d1b0 (cannot verify because private)
- 8a2058b2-6e99-44e1-9adc-4aa05c042b8c
- 57839abe-29d9-45b9-874b-d913b232f93c
- c6f828ab-f0bd-4b75-bb21-ac1d276efe6e (cannot verify because private)
- d17cabe3-d7f2-4ac4-95d8-7c5292dabea4
- 298e1410-3ff6-4868-81d0-e6b8b0be4339
- 45b85714-fd52-4931-818d-ab69d0b07fe8

Duplicates of now-fixed threads that were resubmitted, I've deleted these:

- e7efea56-e93e-4472-80e9-edc4da813b72 (duplicate of 57839abe-29d9-45b9-874b-d913b232f93c)
- e1e179eb-5e02-418a-9426-a45f6fa3e93e (duplicate of 2f1952a0-6d5f-4d1e-beec-ac18a30786e8)

Not fixed:

- 809d8fdd-ba32-49d3-ae46-9f4383bfc145 Didn't manage to fix this as my dumb script doesn't work with complex formatting, this is the only thread with complex formatting. Will keep trying.

**Closed** 2019-01-24 09:08 UTC
Labels: Bug, Bug: FIX NOW

**Comment by brianlovin** [comment] 2019-01-24 15:26
Max. You are a wizard and a master. Amazing job here on the quick fix!
