### ISSUE TITLE
CommunityListItem should be <a>

### ISSUE THREAD

**Issue by lookapanda** [withspectrum/spectrum#4818] opened 2019-03-05 12:39 UTC
Not sure if this is a bug or more a feature; The `CommunityListItem` component should be a link that links to the main page of that community, in my opinion. It could still have the same behavior when clicking on it as it currently does, but additionally, it would be possible to middle-mouse-click / ctrl+click / cmd+click it to open the community in a new tab or right click it to copy the link URL.

This is not possible right now and actually quite confusing, I would have expected that.

**Comment by mxstbr** [comment] 2019-03-05 12:45
There is an open PR for this that we just have to review: #4565! Want to give that a test and comment in there if it works as expected?

**Comment by mxstbr** [comment] 2019-03-05 12:45
Going to close as a duplicate of that 👍

**Closed by mxstbr** 2019-03-05 12:45 UTC
Labels: Feature

**Comment by lookapanda** [comment] 2019-03-05 12:47
Hm, such PRs are hard to find if they don't share the things you were searching for (link, item, etc) haha. Thanks!

**Comment by mxstbr** [comment] 2019-03-05 12:49
Yeah for sure!
